services:
  mysql_banquito:
    image: mysql:8.0
    container_name: mysql_banquito
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banquito_db
    ports:
      - "3306:3306"
    volumes:
      - ./Ex_Banquito_RESTJava/database_script.sql:/docker-entrypoint-initdb.d/01-init.sql
      - mysql_banquito_data:/var/lib/mysql
    networks:
      - app_network

  mysql_comercializadora:
    image: mysql:8.0
    container_name: mysql_comercializadora
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comercializadora_db
    ports:
      - "3307:3306"
    volumes:
      - ./Ex_Comercializadora_RESTJava/database_comercializadora_script.sql:/docker-entrypoint-initdb.d/01-init.sql
      - mysql_comercializadora_data:/var/lib/mysql
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  mysql_banquito_data:
  mysql_comercializadora_data:
